---
title: Hailey :)
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
    layout: blog
- scope:
    path: ''
  values:
    layout: page
description: 
copyright: 
domain: https://haileyvdschans.github.io
baseurl: 
permalink: pretty
