---
title: When worlds collide
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: blog
- scope:
    path: ''
  values:
    layout: page
description: 
domain: https://locke-and-key.github.io
baseurl: 
permalink: pretty
paginate: 10
paginate_path: "/posts/page/:num/"
plugins:
- jekyll-paginate
