---
title: When worlds collide
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: blog
- scope:
    path: ''
  values:
    layout: page
description: 
baseurl: ''
permalink: pretty
paginate: 10
paginate_path: "/posts/page/:num/"
plugins:
- jekyll-paginate
